### ISSUE TITLE
Switch the code to Pep8 standard.

### ISSUE THREAD

**Issue by petitgrizzlies** [cui-unige/mcc4mcc#11]
It's more a request than an issue. Can we convert the code to the Pep8 standard. It's a syntaxe standard used in most of the python project.
The errors to correct are :
-  E272 -> multiple spaces before keyword
- E201 -> whitespace after '['
- E202 -> whitespace before ']'
- E251 -> unexpected spaces around keyword/parameters
- E211 -> whitespaces before '('

**Comment by saucisson** [comment]
My eyes will bleed, but let's do this change.

**Comment by saucisson** [comment]
Also, remove rules from `pylinrc` and fix the code accordingly.

**Comment by saucisson** [comment]
First, fix #16.
