### ISSUE TITLE
Fix removed code that should not

### ISSUE THREAD

**Issue by saucisson** [cui-unige/mcc4mcc#12]
@mencattini  look at 17f9b470db1d05acc1d416ef1751a05fb911b809, it seems that you removed some of my code, that was about distance between tools. Is it intentional?

**Comment by petitgrizzlies** [comment]
I didn't understand why the performance become so bad (cf : https://github.com/cui-unige/mcc4mcc/issues/10). So i tried with old data to test. It was a mistake of my part to push the changes. Sorry.
Do you want i reverse it ?

**Comment by saucisson** [comment]
No thanks, i will do it myself, and perform the benchmark to see if it changes the results.

**Comment by saucisson** [comment]
Put back in 673fcc4453d475e020964d35e38e4fbd5d906284.
You can get the old behavior with:

```sh
./extract.py --distance=0
```

If no distance is given, then all tools that reach the maximum number of instances are considered in the results.
