### ISSUE TITLE
Add scoring function from the MCC

### ISSUE THREAD

**Issue by saucisson** [cui-unige/mcc4mcc#17]
It should compute the score given the [scoring algorithm of the model checking contest](https://mcc.lip6.fr/pdf/rules.pdf).

**Comment by saucisson** [comment]
Using `./extract.py --duplicates=true`, we obtain:

```
INFO: Tool marcie has score 3217.
INFO: Tool gspn has score 3031.
INFO: Tool smart has score 488.
INFO: Tool tedd has score 703.
INFO: Tool sift has score 320.
INFO: Tool spot has score 462.
INFO: Tool ltsmin has score 6575.
INFO: Tool lola has score 7994.
INFO: Tool tapaal has score 3181.
INFO: Tool itstools has score 5065.
INFO: Tool pecan has score 4006.
INFO: Tool pnmc has score 762.
INFO: Tool pnxdd has score 354.
INFO: Tool tapaalEXP has score 2389.
INFO: Tool tapaalPAR has score 2179.
INFO: Tool tapaalSEQ has score 2965.
INFO: Tool yddpt has score 125.
INFO: Algorithm naive-bayes has score 3823.
INFO: Algorithm svm has score 8975.
INFO: Algorithm ada-boost has score 7643.
INFO: Algorithm linear-svm has score 7914.
INFO: Algorithm decision-tree has score 9679.
INFO: Algorithm random-forest has score 9735.
INFO: Algorithm neural-network has score 8009.
INFO: Algorithm decision-tree-regression has score 4357.
INFO: Algorithm knn-regression has score 4360.
INFO: Algorithm random-forest-regression has score 3873.
```

The best algorithm seems to be `random-forest` and it outperforms all tools!

**Comment by saucisson** [comment]
@kyouko-taiga: notice the awful score of `yddpt` ;-)

**Comment by saucisson** [comment]
@mencattini is it possible to print the decision tree obtained by machine learning?

**Comment by petitgrizzlies** [comment]
Is 9735 a good score ?

Yes, it's possible to plot the diagram of the tree. Using `graphviz`, like [here](http://scikit-learn.org/stable/modules/tree.html).

**Comment by saucisson** [comment]
The best tool (lola) has 7.994 points, we get almost 2.000 more! It is not very good, but good enough to win the contest, maybe.

Is it possible to use a vote between the "good" algorithms, for instance svm + ada-boost + linear-svm + decision-tree + random-forest + neural-network?

**Comment by petitgrizzlies** [comment]
Yes it's possible. Just open an issue with this idea. I will implement it. I approve the pull request for the score function.

Has "custom-algo" got good results ?
