### ISSUE TITLE
Add voting between classifier results

### ISSUE THREAD

**Issue by saucisson** [cui-unige/mcc4mcc#29]
Try to enhance results by voting among the results of several algorithms.

**Comment by saucisson** [comment]
The result of voting seems to be always less efficient than the best algorithm.

**Comment by petitgrizzlies** [comment]
It's possible.

Imagine this case : 
 * `algo 1` with score=1000
 * `algo 2` with score=800
 * `algo 3` with score=600

Let imagine that `algo 1` vote for class 1 which is the good answer. `algo 2` and `algo 3` vote for the class 2. The results will be the class 2 : the bad answer.

**Comment by petitgrizzlies** [comment]
I got improvement of score with this : 
```python
    ALGORITHMS["voting-classifier"] = lambda _: VotingClassifier(
        [
            ("decision-tree", DecisionTreeClassifier()),
            ("random-forest", RandomForestClassifier(
                n_estimators=30,
                max_features=None,
            )),
            ("svm", SVC(probability=True))
        ],
        voting='soft'
    )
```
