### ISSUE TITLE
Less data used

### ISSUE THREAD

**Issue by petitgrizzlies** [cui-unige/mcc4mcc#37]
@saucisson 
I have noticed there are less datas than before.
```INFO: Select 9366 best entries.```
And before it was : 
```INFO: Select 10261 best entries.```

Is it normal ?

**Comment by saucisson** [comment]
Yes, because of 22f1e4009b8e30ee3626239ada4630514bc50865. I have renamed tools that were duplicated, for instance: `tapaalSEQ`, `tapaalEXP`, `tapaalPAR` into only one, `tapaal`.
Thus, the removal of duplicates removes more data.

**Comment by petitgrizzlies** [comment]
Ok, thanks for the answer.
I close the issue.
