### ISSUE TITLE
Refactor code into a real python module

### ISSUE THREAD

**Issue by saucisson** [cui-unige/mcc4mcc#41]

**Comment by petitgrizzlies** [comment]
My objectives are :
* use a classic module structure (_inside the `mcc/` folder) for the python, cf [docs.python-guide.org](http://docs.python-guide.org/en/latest/writing/structure/)
* create some files and sort the function by semantics. For exemple, scoring function inside a `score.py`, preprocessing functions inside a `preprocessing.py` or the `extract.py`.

Did i miss something ?

**Comment by saucisson** [comment]
There are some dependencies, for instance parsing the model characteristics and results. Make sure that the module makes it easy, for instance by providing a [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface).

**Comment by petitgrizzlies** [comment]
I tried to change the functions by semantics link with new files. But there is a **huge** amont of code that is hard to just move. I try my best but I don't promise anything.

**Comment by petitgrizzlies** [comment]
@saucisson I worked a lot to this issue. Could you please get a look and tell me your opinion ?

**Comment by saucisson** [comment]
Of course, i will look at it tomorrow.
