### ISSUE TITLE
Fix the distance definition

### ISSUE THREAD

**Issue by petitgrizzlies** [cui-unige/mcc4mcc#8]
diff = x_1 - x_2 
return max(diff, 2)

**Comment by saucisson** [comment]
Fixed by 553b2cce3eba6d9c8821857a71164d6c867abeba

**Comment by saucisson** [comment]
Add a `FIXME` for @mencattini  in 30e0969843f5ed3f95b3783e5300566b43c38ea6 to improve (if needed) the definition of the distance in `knn`.

**Comment by petitgrizzlies** [comment]
Not sure to understand the fixme. This code "clip" the value only if it become greater than `bound`.
Let take an exemple : 
x1 = [1,0,-1,-1], x2 = [1,1,-1,1], then distance = sum ([0,1,0,2]).
x1 =[1, 20, 1], x2 = [1, 10, 1], then distance = sum([0, 10, 0]) which is "cliped" to [0, 2, 0]
x1 = [1, 10, -1, 0], x2 = [1, 5, 1, 1] then distance = sum([0, 5, 2, 1]) which is "cliped" to [0, 2, 2, 1]
By the construction of the array, the value of binary componants can't exceed 2.

Did i miss-understand the initial querry ?

**Comment by saucisson** [comment]
If you have the following vectors: `x1 = [1,0,1,2]` and `x2 = [1,1,-1,3]`, then the result should be `[0,1,2,2]`, because there is a distance of `2` between `-1` and `1`, but also because there is a distance of `2` for the last part, because values are greater than `1`.

**Comment by petitgrizzlies** [comment]
Ok. I didn't understand the mertic on this way.
But is it a problem when there is only one feature that isn't in ternary forme ?

**Comment by saucisson** [comment]
For instance?

**Comment by petitgrizzlies** [comment]
Distance is fixed by 6781f39. Can you check ? (I explain the algorithm in the comments)
